# Generated by Django 4.1.7 on 2023-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='images/'),
            preserve_default=False,
        ),
    ]
